/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bigpharma.view;

import bigpharma.model.AbsModel;
import bigpharma.model.Pessoa;
import bigpharma.model.PessoaFisico;
import bigpharma.model.PessoaJuridico;

/**
 *
 * @author Joyce
 */
public class FConsultaCliente extends javax.swing.JInternalFrame {

    FCadastroPessoaFisica objCadastro;
    FCadastroPessoaJuridica objCadastro2;

    /**
     * Creates new form FCadastroClienteJuridico
     */
    public FConsultaCliente(FCadastroPessoaFisica objCadastro, FCadastroPessoaJuridica objCadastro2) {
        this.objCadastro = objCadastro;
        this.objCadastro2 =objCadastro2;
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabelNome = new javax.swing.JLabel();
        jLabeCPF = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jTextFieldCPF = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButtonBuscar = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setTitle("Consulta Cliente");

        jLabelNome.setText("Nome");

        jLabeCPF.setText("CPF/CNPJ");

        jTextFieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabeCPF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNome)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabeCPF)
                    .addComponent(jTextFieldCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSair)
                .addGap(18, 18, 18)
                .addComponent(jButtonBuscar)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBuscar)
                    .addComponent(jButtonSair))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed

        AbsModel newCliente = null;

        for (int i = 0; i <= ((MainView) MainView.getFrames()[0]).clientes.size(); i++) {

            newCliente = ((MainView) MainView.getFrames()[0]).clientes.get(i);
            boolean resp = ((Pessoa)newCliente).getNome().equals(this.jTextFieldNome.getText());

            if (resp && (((Pessoa)newCliente).getDocumento() == (new Integer(this.jTextFieldCPF.getText())))) {
                i = ((MainView) MainView.getFrames()[0]).clientes.size() + 1;
            }

        }
        if (!((MainView) MainView.getFrames()[0]).clientes.isEmpty()) {
            if (newCliente instanceof PessoaFisico) {
                objCadastro.setjTextFieldNome(((Pessoa)newCliente).getNome());
                objCadastro.setjTextFieldID(newCliente.getId());
                objCadastro.setjTextFieldCNPJ(((Pessoa)newCliente).getDocumento());
                objCadastro.setjTextFieldTelefone(((Pessoa)newCliente).getTelefone());
                objCadastro.setjTextFieldRua(((Pessoa)newCliente).getEndereco().getRua());
                objCadastro.setjTextFieldNumero(((Pessoa)newCliente).getEndereco().getNum());
                objCadastro.setjTextFieldBairro(((Pessoa)newCliente).getEndereco().getBairro());
                objCadastro.setjTextFieldCidade(((Pessoa)newCliente).getEndereco().getCidade());
                objCadastro.setjTextFieldCEP(((Pessoa)newCliente).getEndereco().getCep());
                
//                objCadastro.setjTextFieldsUnable();
//                objCadastro.setjButtonSalvarFalse();
//                objCadastro.setjButtonSalvarModificacaoFalse();
                
                objCadastro.setPessoa((PessoaFisico)newCliente);
                
                objCadastro.setVisible(true);
            } else {
                objCadastro2.setjTextFieldNomeFantasia(((Pessoa)newCliente).getNome());
                objCadastro2.setjTextFieldID(((Pessoa)newCliente).getId());
                objCadastro2.setjTextFieldCNPJ(((Pessoa)newCliente).getDocumento());
                objCadastro2.setjTextFieldTelefone(((Pessoa)newCliente).getTelefone());
                objCadastro2.setjTextFieldRua(((Pessoa)newCliente).getEndereco().getRua());
                objCadastro2.setjTextFieldNumero(((Pessoa)newCliente).getEndereco().getNum());
                objCadastro2.setjTextFieldBairro(((Pessoa)newCliente).getEndereco().getBairro());
                objCadastro2.setjTextFieldCidade(((Pessoa)newCliente).getEndereco().getCidade());
                objCadastro2.setjTextFieldCEP(((Pessoa)newCliente).getEndereco().getCep());
                objCadastro2.setjTextFieldRazaoSocial(((PessoaJuridico)newCliente).getRazaoSocial());
                
//                objCadastro2.setjTextFieldsUnable();
//                objCadastro2.setjButtonSalvarFalse();
//                objCadastro2.setjButtonSalvarModificacaoFalse();
                
                objCadastro2.setPessoa((PessoaJuridico)newCliente);
                
                objCadastro2.setVisible(true);
            }
        }
        //this.setVisible(false);
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButtonSairActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JLabel jLabeCPF;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldCPF;
    private javax.swing.JTextField jTextFieldNome;
    // End of variables declaration//GEN-END:variables
}
